### ISSUE TITLE
When posting data using key navigation on a new key, it ignores key only the first time

### ISSUE THREAD

**Issue by AgeOfMarcus** [neelr/goJSON#2]
Sorry about the title, it's hard to explain what's happening.

# Steps to reproduce

* get a new key with no data
* POST to https://db.neelr.dev/api/{key}/test any data such as `{"a":"hello"}`
* GET to https://db.neelr.dev/api/{key} and notice the response shows `{"a":"hello"}` instead of `{"test":{"a":"hello"}}` as it should
* repeat the earlier post request
* GET to https://db.neelr.dev/api/{key} and now notice the response shows `{"test":{"a":"hello"}, "a":"hello"}`

It seems that the first time data is posted using key navigation in URL the navigation is ignored for some reason but all following times it works correctly

**Comment by neelr** [comment]
Oop yeah, I'll add the nesting logic when creating a record, because it looks like thats whats going on
