### ISSUE TITLE
Any chance you could enable CORS?

### ISSUE THREAD

**Issue by joeskeen** [neelr/goJSON#3]
First off, thank you so much for creating this!

Currently I'm using this in my web apps via a CORS proxy, but it would be great if I could just call it directly from my web app.  Just need `Access-Control-Allow-Origin: *` and `Access-Control-Allow-Method: *` headers return on an HTTP `OPTIONS` call.

**Comment by neelr** [comment]
I see, oops, I'll do that

**Comment by joeskeen** [comment]
One more thing needs to be changed (that I didn't realize until I tried it just now): you need to return a `200 OK` to any `OPTIONS`, even if it doesn't exist, or the CORS policy will reject it:

```
Access to XMLHttpRequest at 'https://db.neelr.dev/api/5a5f801ef552f04c511b6abd21756b32/grave_engelbart' 
from origin 'http://localhost:4200' has been blocked by CORS policy: Response to 
preflight request doesn't pass access control check: It does not have HTTP ok status.
```

In my case I was wanting to `POST` but the browser did a pre-flight `OPTIONS` which returned a `404 NOT FOUND`, so the browser didn't proceed to execute the `POST`.

**Comment by neelr** [comment]
Just tested in browser console, does it work now?

**Comment by joeskeen** [comment]
Yes! Thank you!

**Comment by joeskeen** [comment]
Actually, I guess there are still problems with `DELETE`: 
![image](https://user-images.githubusercontent.com/12286274/81119462-0a9f7280-8ee8-11ea-89e0-51f970a28030.png)

**Comment by neelr** [comment]
Does it work now? I looked into it, and by accident only allowed POST and GET. Should work for GET, POST, PUT, and DELETE now

**Comment by joeskeen** [comment]
Everything seems to be working now!  Thanks for the prompt replies!
