### ISSUE TITLE
All my data was cleared from my JSON database..

### ISSUE THREAD

**Issue by JamzZz** [neelr/goJSON#4]
After about a day everything in my database just disappeared.. I am worried to use this in my app because I can't have data disappearing all the time.

**Comment by neelr** [comment]
Hi! Can you check again just to confirm? Sometimes repl.it goes down. Also it would help if you give me the token (you can use a different one later), just so I can check.

**Comment by JamzZz** [comment]
@neelr Hi. I think what happened is repl.it servers went offline. But, when they came back on, all my data was gone. That's not good for the application I want to use it in.

Thanks so much for creating this by the way, I'd love to continue using it if I could find a solution to this problem.

{p.s. what are you referring to by the "token"? My url was [https://db.neelr.dev/api/zombsbot/](https://db.neelr.dev/api/zombsbot/))

**Comment by JamzZz** [comment]
It happened again!

**Comment by tionis** [comment]
Hosting this on repl.it doesnt seem very stable, why not use something like heroku?
I'm currently throwing something similar together bases on redis using heroku and the free redis database.
